lexer grammar DisplayLexer;

import BasicLexer;

SHOWCOLUMNS : 'SHOWCOLUMNS';
COLUMNWIDTH: 'COLUMNWIDTH';
ALL : 'ALL';
ALTERED : 'ALTERED';
EXCEPT : 'EXCEPT';
COLLAPSED : 'COLLAPSED';
POSITION : 'POSITION';
